### ISSUE TITLE
GPS Items

### ISSUE THREAD

**Issue by vadimaus** [ShawnBaker/Gpmf#2]
What if there are GPS5 and GPS9 coordinates in the GPMF? Do you add them all together ?

**Comment by ShawnBaker** [comment]
No, the code uses the GPS9 items if they exist, or the GPS5 items if there are no GPS9 items. It's always one or the other. In the testing I did, if both existed, it looked like the GPS5 items were duplicates of the GPS9 items, and the GPS9 items are supposed to be more accurate.

On a related note, there was a bug in 1.0.1 that prevented the GPS5 items from being used at all. That's fixed in 1.0.2.
